Import request and Pandas

In [11]:
import pandas as pd
import requests

Set api key

In [12]:
# getting key
#key = pd.read_csv('key.txt', header = None)[0][0]
key = '44437ff083a4c0ff615e4819c9628983'

Set Ticker / Tickers

In [13]:
ticker = ['AAPL']

In [21]:
#https://financialmodelingprep.com/api/v3/income-statement/AAPL?limit=120&apikey=44437ff083a4c0ff615e4819c9628983

URL = 'https://financialmodelingprep.com/api/v3/'
IS = 'income-statement/'
ticker = ticker[0]
period ='annual' #'quarter
limit = 20
r = requests.get('{}{}{}?period={}&limit={}&apikey={}'.format(URL, IS, ticker, period, limit, key))

In [22]:
r

format income statement data to json format

In [25]:
incomeStatement = r.json()

In [28]:
type(r.json())
type(r.json()[0])

dict

turn data to a table

In [33]:
data = pd.DataFrame.from_dict(r.json()).transpose()

In [34]:
data.columns = data.iloc[0]
data = data.iloc[1:]

In [35]:
data

date,2021-10-31,2020-10-31,2019-10-31,2018-10-31,2017-10-31
symbol,A,A,A,A,A
reportedCurrency,USD,USD,USD,USD,USD
cik,0001090872,0001090872,0001090872,0001090872,0001090872
fillingDate,2021-12-17,2020-12-18,2019-12-19,2018-12-20,2017-12-21
acceptedDate,2021-12-17 17:01:49,2020-12-17 19:56:21,2019-12-19 17:11:01,2018-12-20 16:27:07,2017-12-21 16:27:19
calendarYear,2021,2020,2019,2018,2017
period,FY,FY,FY,FY,FY
revenue,6319000000,5339000000,5163000000,4914000000,4472000000
costOfRevenue,2912000000,2502000000,2358000000,2227000000,2063000000
grossProfit,3407000000,2837000000,2805000000,2687000000,2409000000
grossProfitRatio,0.539168,0.531373,0.543289,0.546805,0.538685
researchAndDevelopmentExpenses,441000000,495000000,404000000,385000000,339000000
generalAndAdministrativeExpenses,0.0,1496000000.0,1460000000.0,1374000000.0,1229000000.0
sellingAndMarketingExpenses,0.0,0.0,0.0,0.0,0.0
sellingGeneralAndAdministrativeExpenses,1619000000,1496000000,1460000000,1374000000,1229000000
otherExpenses,0.0,0.0,0.0,0.0,0.0
operatingExpenses,2060000000,1991000000,1864000000,1759000000,1568000000
costAndExpenses,4972000000,4493000000,4222000000,3986000000,3631000000
interestIncome,2000000.0,8000000.0,36000000.0,38000000.0,22000000.0
interestExpense,81000000,78000000,74000000,75000000,79000000
depreciationAndAmortization,321000000,308000000,238000000,210000000,212000000
ebitda,1762000000,1228000000,1231000000,1231000000,1094000000
ebitdaratio,0.278842,0.230006,0.238427,0.250509,0.244633
operatingIncome,1347000000,846000000,941000000,928000000,841000000
operatingIncomeRatio,0.213167,0.158457,0.182258,0.188848,0.188059
totalOtherIncomeExpensesNet,13000000.0,-4000000.0,-22000000.0,18000000.0,-38000000.0
incomeBeforeTax,1360000000,842000000,919000000,946000000,803000000
incomeBeforeTaxRatio,0.215224,0.157707,0.177997,0.192511,0.179562
incomeTaxExpense,150000000,123000000,-152000000,630000000,119000000
netIncome,1210000000,719000000,1071000000,316000000,684000000
netIncomeRatio,0.191486,0.134669,0.207438,0.064306,0.152952
eps,3.98,2.33,3.41,0.98,2.12
epsdiluted,3.94,2.3,3.37,0.97,2.1
weightedAverageShsOut,304000000,309000000,314000000,321000000,322000000
weightedAverageShsOutDil,307000000,312000000,318000000,325000000,326000000
link,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...
finalLink,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...,https://www.sec.gov/Archives/edgar/data/109087...

          Revenue    Earnings
Year
2018  17049000000  2651000000
2019  17911000000  3008000000
2020  22284000000  3646000000
2021  29453000000  6433000000

,Max Age,End Date,Growth,Earnings Estimate Avg,Earnings Estimate Low,Earnings Estimate High,Earnings Estimate Year Ago Eps,Earnings Estimate Number Of Analysts,Earnings Estimate Growth,Revenue Estimate Avg,...,Revenue Estimate Growth,Eps Trend Current,Eps Trend 7Days Ago,Eps Trend 30Days Ago,Eps Trend 60Days Ago,Eps Trend 90Days Ago,Eps Revisions Up Last7Days,Eps Revisions Up Last30Days,Eps Revisions Down Last30Days,Eps Revisions Down Last90Days
Period,,,,,,,,,,,,,,,,,,,,,
0Q,1,2022-06-30,-0.04100,2.36,2.29,2.60,2.46,19.0,-0.041,7.322300e+09,...,0.089,2.36,2.36,2.37,2.52,2.52,0.0,0.0,0.0,NaN
+1Q,1,2022-09-30,-0.01700,2.35,2.25,2.61,2.39,19.0,-0.017,7.345500e+09,...,NaN,2.35,2.35,2.35,2.46,2.46,0.0,0.0,0.0,NaN
0Y,1,2022-12-31,0.02800,10.33,10.19,10.94,10.05,21.0,0.028,3.070780e+10,...,0.043,10.33,10.33,10.34,10.45,10.44,0.0,1.0,0.0,NaN
+1Y,1,2023-12-31,0.05800,10.93,10.48,11.50,10.33,20.0,0.058,3.218690e+10,...,0.048,10.93,10.93,10.90,10.98,10.94,0.0,1.0,0.0,NaN
+5Y,1,NaT,0.11050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-5Y,1,NaT,0.02935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,2021-12-31,2020-12-31,2019-12-31,2018-12-31
Research Development,1742000000.0,1348000000.0,1126000000.0,1059000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,7598000000.0,4495000000.0,3305000000.0,2962000000.0
Minority Interest,10000000.0,11000000.0,11000000.0,12300000.0
Net Income,6433000000.0,3646000000.0,3008000000.0,2651000000.0
Selling General Administrative,8146000000.0,6858000000.0,5577000000.0,5356000000.0
Gross Profit,18056000000.0,13043000000.0,9984000000.0,9505000000.0
Ebit,8168000000.0,4837000000.0,3281000000.0,3090000000.0
Operating Income,8168000000.0,4837000000.0,3281000000.0,3090000000.0
Other Operating Expenses,None,None,None,None
Interest Expense,-238000000.0,-275000000.0,-108000000.0,-137000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,1251000000.0,849000000.0,873000000.0,556000000.0
Total Revenue,29453000000.0,22284000000.0,17911000000.0,17049000000.0
Total Operating Expenses,21285000000.0,17447000000.0,14630000000.0,13959000000.0
Cost Of Revenue,11397000000.0,9241000000.0,7927000000.0,7544000000.0
Total Other Income Expense Net,-570000000.0,-342000000.0,24000000.0,-128000000.0
Discontinued Operations,86000000.0,86000000.0,576000000.0,245000000.0
Net Income From Continuing Ops,6347000000.0,3646000000.0,2432000000.0,2406000000.0
Net Income Applicable To Common Shares,6269000000.0,3510000000.0,2940000000.0,2651000000.0

,2021-12-31,2020-12-31,2019-12-31,2018-12-31
Research Development,1742000000.0,1348000000.0,1126000000.0,1059000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,7598000000.0,4495000000.0,3305000000.0,2962000000.0
Minority Interest,10000000.0,11000000.0,11000000.0,12300000.0
Net Income,6433000000.0,3646000000.0,3008000000.0,2651000000.0
...,...,...,...,...
Change To Inventory,-502000000.0,-123000000.0,-22000000.0,-134000000.0
Change To Account Receivables,-611000000.0,-264000000.0,-157000000.0,-55000000.0
Other Cashflows From Financing Activities,-112000000.0,-29000000.0,369000000.0,-18000000.0
Change To Netincome,415000000.0,208000000.0,-115000000.0,271000000.0
Capital Expenditures,-1294000000.0,-791000000.0,-636000000.0,-584000000.0

,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,Other Operating Expenses,...,Effect Of Exchange Rate,Total Cash From Operating Activities,Depreciation,Other Cashflows From Investing Activities,Dividends Paid,Change To Inventory,Change To Account Receivables,Other Cashflows From Financing Activities,Change To Netincome,Capital Expenditures
,,,,,,,,,,,,,,,,,,,,,
2021-12-31,1742000000.0,None,7598000000.0,10000000.0,6433000000.0,8146000000.0,18056000000.0,8168000000.0,8168000000.0,None,...,-115000000.0,8358000000.0,2168000000.0,37000000.0,-742000000.0,-502000000.0,-611000000.0,-112000000.0,415000000.0,-1294000000.0
2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6858000000.0,13043000000.0,4837000000.0,4837000000.0,None,...,148000000.0,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,208000000.0,-791000000.0
2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,None,...,45000000.0,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-115000000.0,-636000000.0
2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,None,...,-118000000.0,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0

download fundamental data for multiple tickers

['fb', 'amzn', 'nflx', 'goog']

[yfinance.Ticker object <FB>,
 yfinance.Ticker object <AMZN>,
 yfinance.Ticker object <NFLX>,
 yfinance.Ticker object <GOOG>]

,Data,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,...,Total Cash From Operating Activities,Depreciation,Other Cashflows From Investing Activities,Dividends Paid,Change To Inventory,Change To Account Receivables,Other Cashflows From Financing Activities,Change To Netincome,Capital Expenditures,Ticker
0,2021-12-31,1742000000.0,None,7598000000.0,10000000.0,6433000000.0,8146000000.0,18056000000.0,8168000000.0,8168000000.0,...,8358000000.0,2168000000.0,37000000.0,-742000000.0,-502000000.0,-611000000.0,-112000000.0,415000000.0,-1294000000.0,GOOG
1,2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6858000000.0,13043000000.0,4837000000.0,4837000000.0,...,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,208000000.0,-791000000.0,GOOG
2,2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,...,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-115000000.0,-636000000.0,GOOG
3,2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,...,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0,GOOG

C:\Users\enoma\AppData\Local\Temp\ipykernel_10536\2303959853.py:7: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only.
  df = df.set_index('Ticker', 'Data')

,Data,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,...,Effect Of Exchange Rate,Total Cash From Operating Activities,Depreciation,Other Cashflows From Investing Activities,Dividends Paid,Change To Inventory,Change To Account Receivables,Other Cashflows From Financing Activities,Change To Netincome,Capital Expenditures
Ticker,,,,,,,,,,,,,,,,,,,,,
FB,2021-12-31,1742000000.0,None,7598000000.0,10000000.0,6433000000.0,8146000000.0,18056000000.0,8168000000.0,8168000000.0,...,-115000000.0,8358000000.0,2168000000.0,37000000.0,-742000000.0,-502000000.0,-611000000.0,-112000000.0,415000000.0,-1294000000.0
FB,2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6858000000.0,13043000000.0,4837000000.0,4837000000.0,...,148000000.0,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,208000000.0,-791000000.0
FB,2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,...,45000000.0,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-115000000.0,-636000000.0
FB,2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,...,-118000000.0,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0
AMZN,2021-12-31,1742000000.0,None,7598000000.0,10000000.0,6433000000.0,8146000000.0,18056000000.0,8168000000.0,8168000000.0,...,-115000000.0,8358000000.0,2168000000.0,37000000.0,-742000000.0,-502000000.0,-611000000.0,-112000000.0,415000000.0,-1294000000.0
AMZN,2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6858000000.0,13043000000.0,4837000000.0,4837000000.0,...,148000000.0,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,208000000.0,-791000000.0
AMZN,2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,...,45000000.0,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-115000000.0,-636000000.0
AMZN,2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,...,-118000000.0,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0
NFLX,2021-12-31,1742000000.0,None,7598000000.0,10000000.0,6433000000.0,8146000000.0,18056000000.0,8168000000.0,8168000000.0,...,-115000000.0,8358000000.0,2168000000.0,37000000.0,-742000000.0,-502000000.0,-611000000.0,-112000000.0,415000000.0,-1294000000.0
NFLX,2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6858000000.0,13043000000.0,4837000000.0,4837000000.0,...,148000000.0,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,208000000.0,-791000000.0
NFLX,2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,...,45000000.0,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-115000000.0,-636000000.0
NFLX,2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,...,-118000000.0,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0
GOOG,2021-12-31,1742000000.0,None,7598000000.0,10000000.0,6433000000.0,8146000000.0,18056000000.0,8168000000.0,8168000000.0,...,-115000000.0,8358000000.0,2168000000.0,37000000.0,-742000000.0,-502000000.0,-611000000.0,-112000000.0,415000000.0,-1294000000.0
GOOG,2020-12-31,1348000000.0,None,4495000000.0,11000000.0,3646000000.0,6858000000.0,13043000000.0,4837000000.0,4837000000.0,...,148000000.0,6208000000.0,1775000000.0,24000000.0,-615000000.0,-123000000.0,-264000000.0,-29000000.0,208000000.0,-791000000.0
GOOG,2019-12-31,1126000000.0,None,3305000000.0,11000000.0,3008000000.0,5577000000.0,9984000000.0,3281000000.0,3281000000.0,...,45000000.0,3952000000.0,1189000000.0,-43000000.0,-527000000.0,-22000000.0,-157000000.0,369000000.0,-115000000.0,-636000000.0
GOOG,2018-12-31,1059000000.0,None,2962000000.0,12300000.0,2651000000.0,5356000000.0,9505000000.0,3090000000.0,3090000000.0,...,-118000000.0,4022000000.0,1178000000.0,-74000000.0,-433000000.0,-134000000.0,-55000000.0,-18000000.0,271000000.0,-584000000.0

How to Get Options Data

yfinance.Ticker object <AAPL>

Options(calls=          contractSymbol             lastTradeDate   strike  lastPrice  \
0    AAPL220617C00028750 2022-06-10 17:49:25+00:00    28.75     109.70
1    AAPL220617C00030000 2022-06-15 16:46:01+00:00    30.00     105.60
2    AAPL220617C00031250 2022-06-10 13:59:59+00:00    31.25     107.15
3    AAPL220617C00032500 2022-06-03 15:10:12+00:00    32.50     112.40
4    AAPL220617C00033750 2022-06-07 18:43:00+00:00    33.75     114.75
..                   ...                       ...      ...        ...
150  AAPL220617C00680000 2020-08-27 16:59:15+00:00   680.00     333.83
151  AAPL220617C00700000 2020-08-28 19:12:54+00:00   700.00    1125.00
152  AAPL220617C00720000 2020-08-28 16:29:09+00:00   720.00    1106.80
153  AAPL220617C00740000 2020-08-28 17:46:32+00:00   740.00     932.00
154  AAPL220617C01000000 2020-08-28 19:48:09+00:00  1000.00      20.31

        bid     ask       change  percentChange  volume  openInterest  \
0    105.75  107.20     0.000000       0.000000       1            16
1    104.75  106.30    -2.849998      -2.627938      33             6
2    103.65  104.70     0.000000       0.000000       1             1
3    102.15  103.60     0.000000       0.000000       1            35
4    100.90  102.35     0.000000       0.000000       1            12
..      ...     ...          ...            ...     ...           ...
150  329.00  334.00   283.629970     564.999940      30           146
151  324.00  329.00  1079.200000    2356.331800     127            52
152  319.50  324.50  1063.550000    2459.075200       1           362
153  315.00  320.00   891.000000    2173.170700       7            78
154   18.85   20.15     1.359999       7.176774      51            29

     impliedVolatility  inTheMoney contractSize currency
0            10.992191        True      REGULAR      USD
1             8.390630        True      REGULAR      USD
2            10.414066        True      REGULAR      USD
3            10.605472        True      REGULAR      USD
4            10.335941        True      REGULAR      USD
..                 ...         ...          ...      ...
150           0.000000       False      REGULAR      USD
151           0.000000       False      REGULAR      USD
152           0.000000       False      REGULAR      USD
153           0.000000       False      REGULAR      USD
154          20.326664       False      REGULAR      USD

[155 rows x 14 columns], puts=          contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0    AAPL220617P00028750 2022-06-15 14:17:40+00:00   28.75       0.01    0.00
1    AAPL220617P00030000 2022-06-13 14:21:52+00:00   30.00       0.01    0.00
2    AAPL220617P00031250 2022-02-08 14:30:04+00:00   31.25       0.02    0.00
3    AAPL220617P00032500 2022-03-22 15:12:03+00:00   32.50       0.02    0.00
4    AAPL220617P00033750 2022-05-12 16:05:32+00:00   33.75       0.01    0.00
..                   ...                       ...     ...        ...     ...
142  AAPL220617P00600000 2020-08-27 16:53:15+00:00  600.00     170.00  166.65
143  AAPL220617P00640000 2020-08-07 14:08:26+00:00  640.00     218.72  196.65
144  AAPL220617P00700000 2020-08-24 18:56:07+00:00  700.00      18.60    4.55
145  AAPL220617P00720000 2020-08-24 18:56:07+00:00  720.00       5.06    4.90
146  AAPL220617P00800000 2020-08-27 13:54:52+00:00  800.00       6.65    6.50

        ask  change  percentChange  volume  openInterest  impliedVolatility  \
0      0.00    0.00       0.000000     3.0        1645.0           0.500005
1      0.01    0.00       0.000000     2.0        2813.0           6.250002
2      0.00    0.00       0.000000     2.0         440.0           0.500005
3      0.02    0.00       0.000000     1.0         514.0           6.375002
4      0.05    0.00       0.000000    20.0         394.0           6.687502
..      ...     ...            ...     ...           ...                ...
142  169.80    0.00       0.000000     NaN           2.0           0.000010
143  200.10    0.00       0.000000     1.0           1.0           0.000010
144    4.80 -222.86     -92.296860     4.0         413.0           0.000010
145    5.20 -253.00     -98.039215     2.0         669.0           0.000010
146    7.35 -315.70     -97.937030    31.0         900.0           0.000010

     inTheMoney contractSize currency
0         False      REGULAR      USD
1         False      REGULAR      USD
2         False      REGULAR      USD
3         False      REGULAR      USD
4         False      REGULAR      USD
..          ...          ...      ...
142        True      REGULAR      USD
143        True      REGULAR      USD
144        True      REGULAR      USD
145        True      REGULAR      USD
146        True      REGULAR      USD

[147 rows x 14 columns])

('2022-06-17',
 '2022-06-24',
 '2022-07-01',
 '2022-07-08',
 '2022-07-15',
 '2022-07-22',
 '2022-07-29',
 '2022-08-19',
 '2022-09-16',
 '2022-10-21',
 '2022-11-18',
 '2022-12-16',
 '2023-01-20',
 '2023-03-17',
 '2023-06-16',
 '2023-09-15',
 '2024-01-19',
 '2024-06-21')

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL220617P00028750,2022-06-15 14:17:40+00:00,28.75,0.01,0.00,0.00,0.00,0.000000,3.0,1645.0,0.500005,False,REGULAR,USD
1,AAPL220617P00030000,2022-06-13 14:21:52+00:00,30.00,0.01,0.00,0.01,0.00,0.000000,2.0,2813.0,6.250002,False,REGULAR,USD
2,AAPL220617P00031250,2022-02-08 14:30:04+00:00,31.25,0.02,0.00,0.00,0.00,0.000000,2.0,440.0,0.500005,False,REGULAR,USD
3,AAPL220617P00032500,2022-03-22 15:12:03+00:00,32.50,0.02,0.00,0.02,0.00,0.000000,1.0,514.0,6.375002,False,REGULAR,USD
4,AAPL220617P00033750,2022-05-12 16:05:32+00:00,33.75,0.01,0.00,0.05,0.00,0.000000,20.0,394.0,6.687502,False,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,AAPL220617P00600000,2020-08-27 16:53:15+00:00,600.00,170.00,166.65,169.80,0.00,0.000000,NaN,2.0,0.000010,True,REGULAR,USD
143,AAPL220617P00640000,2020-08-07 14:08:26+00:00,640.00,218.72,196.65,200.10,0.00,0.000000,1.0,1.0,0.000010,True,REGULAR,USD
144,AAPL220617P00700000,2020-08-24 18:56:07+00:00,700.00,18.60,4.55,4.80,-222.86,-92.296860,4.0,413.0,0.000010,True,REGULAR,USD
145,AAPL220617P00720000,2020-08-24 18:56:07+00:00,720.00,5.06,4.90,5.20,-253.00,-98.039215,2.0,669.0,0.000010,True,REGULAR,USD
146,AAPL220617P00800000,2020-08-27 13:54:52+00:00,800.00,6.65,6.50,7.35,-315.70,-97.937030,31.0,900.0,0.000010,True,REGULAR,USD

How to Get Institutional Holders Using yfinance

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",1269995750,2022-03-30,0.0785,221753957907
1,Blackrock Inc.,1027632887,2022-03-30,0.0635,179434978399
2,"Berkshire Hathaway, Inc",890923410,2022-03-30,0.0550,155564136620
3,State Street Corporation,613852274,2022-03-30,0.0379,107184745563
4,"FMR, LLC",351584762,2022-03-30,0.0217,61390215292
5,"Geode Capital Management, LLC",272081668,2022-03-30,0.0168,47508180049
6,Price (T.Rowe) Associates Inc,233079365,2022-03-30,0.0144,40697987922
7,Northern Trust Corporation,186031985,2022-03-30,0.0115,32483044900
8,Bank of America Corporation,144401747,2022-03-30,0.0089,25213989043
9,Norges Bank Investment Management,142076403,2021-12-30,0.0088,25228506880

Why You Shouldn't Use Yahoo Finance for Live Trading

,2021-12-31,2020-12-31,2019-12-31,2018-12-31
Investments,1.213200e+10,-1.452000e+10,-4.254000e+09,2.449000e+09
Change To Liabilities,1.623000e+09,9.100000e+07,2.360000e+08,2.740000e+08
Total Cashflows From Investing Activities,-7.570000e+09,-3.005900e+10,-1.986400e+10,-1.160300e+10
Net Borrowings,-6.630000e+08,-5.800000e+08,-7.750000e+08,5.000000e+08
Total Cash From Financing Activities,-5.072800e+10,-1.029200e+10,-7.299000e+09,-1.557200e+10
Change To Operating Activities,2.187000e+09,-1.302000e+09,8.975000e+09,9.100000e+07
Net Income,3.937000e+10,2.914600e+10,1.848500e+10,2.211200e+10
Change In Cash,-1.089000e+09,-1.325000e+09,9.155000e+09,1.920000e+09
Repurchase Of Stock,-5.005200e+10,-9.836000e+09,-6.539000e+09,-1.608700e+10
Effect Of Exchange Rate,-4.740000e+08,2.790000e+08,4.000000e+06,-1.790000e+08
Total Cash From Operating Activities,5.768300e+10,3.874700e+10,3.631400e+10,2.927400e+10
Depreciation,7.967000e+09,6.862000e+09,5.741000e+09,4.315000e+09
Other Cashflows From Investing Activities,-2.840000e+08,-3.600000e+07,-3.600000e+07,-3.600000e+07
Change To Account Receivables,-3.110000e+09,-1.512000e+09,-1.961000e+09,-1.892000e+09
Other Cashflows From Financing Activities,-1.300000e+07,1.240000e+08,1.500000e+07,1.500000e+07
Change To Netincome,9.646000e+09,5.462000e+09,4.838000e+09,4.374000e+09
Capital Expenditures,-1.856700e+10,-1.511500e+10,-1.510200e+10,-1.391500e+10

,2021-12-31,2020-12-31,2019-12-31,2018-12-31
Investments,1.213200e+10,-1.452000e+10,-4.254000e+09,2.449000e+09
Change To Liabilities,1.623000e+09,9.100000e+07,2.360000e+08,2.740000e+08
Total Cashflows From Investing Activities,-7.570000e+09,-3.005900e+10,-1.986400e+10,-1.160300e+10
Net Borrowings,-6.630000e+08,-5.800000e+08,-7.750000e+08,5.000000e+08
Total Cash From Financing Activities,-5.072800e+10,-1.029200e+10,-7.299000e+09,-1.557200e+10
Change To Operating Activities,2.187000e+09,-1.302000e+09,8.975000e+09,9.100000e+07
Net Income,3.937000e+10,2.914600e+10,1.848500e+10,2.211200e+10
Change In Cash,-1.089000e+09,-1.325000e+09,9.155000e+09,1.920000e+09
Repurchase Of Stock,-5.005200e+10,-9.836000e+09,-6.539000e+09,-1.608700e+10
Effect Of Exchange Rate,-4.740000e+08,2.790000e+08,4.000000e+06,-1.790000e+08
Total Cash From Operating Activities,5.768300e+10,3.874700e+10,3.631400e+10,2.927400e+10
Depreciation,7.967000e+09,6.862000e+09,5.741000e+09,4.315000e+09
Other Cashflows From Investing Activities,-2.840000e+08,-3.600000e+07,-3.600000e+07,-3.600000e+07
Change To Account Receivables,-3.110000e+09,-1.512000e+09,-1.961000e+09,-1.892000e+09
Other Cashflows From Financing Activities,-1.300000e+07,1.240000e+08,1.500000e+07,1.500000e+07
Change To Netincome,9.646000e+09,5.462000e+09,4.838000e+09,4.374000e+09
Capital Expenditures,-1.856700e+10,-1.511500e+10,-1.510200e+10,-1.391500e+10